### ISSUE TITLE
Error coming from `invoke.d.ts`

### ISSUE THREAD

**Issue by eric-simonton-sama** [simontonsoftware/micro-dash#33]
ERROR in node_modules/micro-dash/lib/object/invoke.d.ts:47:25 - error TS2589: Type instantiation is excessively deep and possibly infinite.

47 export declare function invoke<K1 extends Key, K2 extends Key, K3 extends Key, K4 extends Key, T extends Obj4<K1, K2, K3, K4, Fn> | Nil>(object: T, path: [K1, K2, K3, K4], ...args: Parameters<DefinedPath4<K1, K2, K3, K4, T>>): Path4<K1, K2, K3, K4, T> extends DefinedPath4<K1, K2, K3, K4, T> ? ReturnType<DefinedPath4<K1, K2, K3, K4, T>> : ReturnType<DefinedPath4<K1, K2, K3, K4, T>> | undefined;
                           ~~~~~~

**Comment by ersimont** [comment]
For a workaround until fixed, you can use `skipLibCheck: true` in your `tsconfig.json`.
