### ISSUE TITLE
Re-release Docs

### ISSUE THREAD

**Issue by luhis** [simontonsoftware/micro-dash#52]
Hi,

I see you have added some new functions, e.g. groupBy, but I only found it by looking at the issues.

Could you update the docs at https://simontonsoftware.github.io/micro-dash/typedoc/ ?

Matt

**Comment by ersimont** [comment]
Done! Actually, they were not in the docs because those functions had not been released yet. So I released them in version 8.1 AND published the updated docs. :)

Good eye, and I'm glad you found the library worth looking into. Thanks!
