### ISSUE TITLE
No readme found an npmjs.com

### ISSUE THREAD

**Issue by qruplay** [simontonsoftware/micro-dash#53]
Hi!

Really interested in micro-dash lib!

Searched it at npmjs.com and found out, that it has missing Readme.
https://www.npmjs.com/package/micro-dash

It's not that big an issue, but maybe it will help lib to be more popular!

**Comment by ersimont** [comment]
Interesting. Thank you for letting me know! I always look at package directly in github, so this slipped my notice.

I'm in the process of migrating a number libraries to a monorepo, including this one. I'll leave this issue open to remind me to set it up better over there!

**Comment by ersimont** [comment]
The new package from the Monorepo looks to have a readme! I didn't even have to set it up manually - I guess the newer CLI I'm using does it automatically now. The new setup is not quite ready for production yet, but I'm chipping away at it.

Thanks again! Closing this issue.
