### ISSUE TITLE
Support for deep cloning dates?

### ISSUE THREAD

**Issue by RaphiStein** [simontonsoftware/micro-dash#54]
`cloneDeep` does not handle Date objects as I would expect.
Is this expected behaviour for micro-dash?

For example, for:

```
const obj = {
  thedate: new Date()
}
console.log(cloneDeep(obj)));
```

I expected:

`{ thedate: "2020-10-26T01:42:00.962Z" }`

Actual:

`{ thedate: {} }`

**Comment by ersimont** [comment]
That is not surprising. From the readme under "differences from lodash":

> Only designed to work with primitives, plain objects, and arrays. It is not designed or tested to handle inherited properties, symbol keys, arguments objects, primitive objects (e.g. Object(1)), Dates, Maps, Sets, etc.

This library is meant to work with the kinda of objects you send receive over network calls, and keep in a store (which at least for ngrx/store is the same).
